apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ns57aoahe-python 
  janus-idp.io/tekton: ns57aoahe-python
  backstage.io/kubernetes-id: ns57aoahe-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ns57aoahe-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  