apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ns57aoahe-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ns57aoahe-python 
  name: ns57aoahe-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ns57aoahe-python 
